# Generated by Django 2.2.28 on 2022-11-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_empty', models.BooleanField()),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('race', models.CharField(max_length=20)),
                ('order', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=200)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.Equipement')),
            ],
        ),
    ]
