# Generated by Django 2.2.28 on 2022-11-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
