# Generated by Django 4.1.3 on 2022-11-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0002_auto_20221120_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='is_empty',
        ),
        migrations.AddField(
            model_name='equipement',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipement',
            name='occupation',
            field=models.IntegerField(default=0),
        ),
    ]
