# Generated by Django 3.2.16 on 2022-11-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_remove_equipement_is_empty_equipement_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='state_after',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='equipement',
            name='state_before',
            field=models.CharField(default='', max_length=20),
        ),
    ]
